version: '3.8'
services:

  hills.test:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
      target: develop
    image: dowhilenotdone/nginx:latest    
    container_name: hills-app-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8881:8881"
      - "8443:443"
    volumes:
        - ./:/var/www
        - ./docker/config/nginx/conf.d/hillstest.conf:/etc/nginx/conf.d/default.conf:ro
        - ./docker/config/nginx/conf.d/mime.types:/etc/nginx/conf.d/mime.types:ro

  hills-app-php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/php-fpm/Dockerfile
      target: develop
    image: dowhilenotdone/php-fpm:latest
    container_name: hills-app-php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  hills-app-vite:
    image: node:18
    container_name: hills-app-vite
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm run dev"
    ports:
      - "5173:5173"

  hills-app-mysql:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
      target: develop
    image: dowhilenotdone/mysql:latest
    container_name: hills-app-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - $PWD/docker/volumes/mysql:/var/lib/mysql
      - $PWD/docker/config/mysql/my.cnf:/etc/mysql/my.cnf
      - $PWD/docker/config/mysql/init/create-databases.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass

  hills-app-mailtrap:
    image: eaudeweb/mailtrap:latest
    container_name: hills-app-mailtrap
    environment:
      - MT_USER=mailtrap
      - MT_PASSWD=mailtrap
    ports:
      - "2225:25"
      - "8882:80"

  hills-app-selenium:
    container_name: hills-app-selenium
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444    
    shm_size: '2gb'
