name: Laravel CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout step
              uses: actions/checkout@v3
            - name: Todo Docker Layer Caching Cache
              id: docker-cache
              run: |
                  echo "TODO: Docker Layer Cache"
            - name: Start Docker Containers
              run: |
                  docker compose up -d
            - name: Todo Composer Cache
              id: composer-cache
              run: |
                  echo "TODO: Composer Cache"
            - name: Composer step
              run: docker compose exec hills-app-php-fpm composer install
            - name: Configure Site
              run: |
                  chmod -R 777 storage
                  mkdir -m 777 coverage
                  cp .env.docker .env
                  docker compose exec hills-app-php-fpm php artisan key:generate
            - name: Include Node
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Todo Node Cache
              id: node-cache
              run: |
                  echo "TODO: Node Cache"
            - name: Create Node Assets
              run: |
                  npm install
                  npm run build
            - name: Wait for mysql
              run: |
                  echo 'pausing: waiting for mysql to come available'
                  ./docker/config/mysql/.wait-for-mysql.sh
                  echo 'un-pausing: mysql is now available'
            - name: PHP Test Step
              run: docker exec hills-app-php-fpm php artisan test
            - name: Todo Test Coverage
              id: coverage-cache
              run: |
                  echo "TODO: Test Coverage"
            - name: Todo Upload Assets
              id: assets-cache
              run: |
                  echo "TODO: Upload Assets"
